-- =========================================================
-- MIGRATION 002 v2: Fix app_user schema (handles different scenarios)
-- =========================================================
-- This migration handles multiple scenarios:
-- 1. Table doesn't exist -> create from scratch
-- 2. Table exists with user_id -> rename to auth_user_id
-- 3. Table exists with auth_user_id -> add missing columns
-- =========================================================

DO $$
BEGIN
  -- Check if app_user table exists
  IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'app_user') THEN
    -- Scenario 1: Table doesn't exist - create it from scratch
    RAISE NOTICE 'Creating app_user table from scratch';
    
    CREATE TABLE public.app_user (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      auth_user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
      email TEXT NOT NULL,
      role_id INTEGER NOT NULL REFERENCES public.role(id) ON DELETE RESTRICT,
      client_id BIGINT REFERENCES public.client(id) ON DELETE SET NULL,
      is_active BOOLEAN DEFAULT true,
      last_login TIMESTAMPTZ,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
    
    CREATE INDEX idx_app_user_role ON public.app_user(role_id);
    CREATE INDEX idx_app_user_client ON public.app_user(client_id);
    CREATE INDEX idx_app_user_auth_user_id ON public.app_user(auth_user_id);
    CREATE INDEX idx_app_user_email ON public.app_user(email);
    
    COMMENT ON TABLE public.app_user IS 'Profil applicatif lié à Supabase auth.users';
    
  ELSE
    -- Table exists - check which columns are present
    RAISE NOTICE 'app_user table exists, checking schema';
    
    -- Check if we have user_id (old schema)
    IF EXISTS (
      SELECT FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'app_user' 
      AND column_name = 'user_id'
    ) THEN
      -- Scenario 2: Has user_id, needs to be renamed to auth_user_id
      RAISE NOTICE 'Renaming user_id to auth_user_id';
      
      -- Drop PK constraint on user_id
      ALTER TABLE public.app_user DROP CONSTRAINT IF EXISTS app_user_pkey;
      
      -- Rename column
      ALTER TABLE public.app_user RENAME COLUMN user_id TO auth_user_id;
      
      -- Add id as new PK
      IF NOT EXISTS (
        SELECT FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'app_user' 
        AND column_name = 'id'
      ) THEN
        ALTER TABLE public.app_user ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
      END IF;
      
      -- Add unique constraint on auth_user_id
      ALTER TABLE public.app_user ADD CONSTRAINT app_user_auth_user_id_key UNIQUE (auth_user_id);
      
    END IF;
    
    -- Scenario 3: Add missing columns if they don't exist
    
    -- Add id column if missing
    IF NOT EXISTS (
      SELECT FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'app_user' 
      AND column_name = 'id'
    ) THEN
      RAISE NOTICE 'Adding id column';
      ALTER TABLE public.app_user DROP CONSTRAINT IF EXISTS app_user_pkey;
      ALTER TABLE public.app_user ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    END IF;
    
    -- Add auth_user_id column if missing (shouldn't happen, but just in case)
    IF NOT EXISTS (
      SELECT FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'app_user' 
      AND column_name = 'auth_user_id'
    ) THEN
      RAISE NOTICE 'Adding auth_user_id column';
      ALTER TABLE public.app_user ADD COLUMN auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE;
    END IF;
    
    -- Add email column if missing
    IF NOT EXISTS (
      SELECT FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'app_user' 
      AND column_name = 'email'
    ) THEN
      RAISE NOTICE 'Adding email column';
      ALTER TABLE public.app_user ADD COLUMN email TEXT;
      
      -- Populate email from auth.users for existing records
      UPDATE public.app_user au
      SET email = (
        SELECT email 
        FROM auth.users 
        WHERE id = au.auth_user_id
      )
      WHERE email IS NULL AND auth_user_id IS NOT NULL;
      
      -- Make email NOT NULL after population
      ALTER TABLE public.app_user ALTER COLUMN email SET NOT NULL;
    END IF;
    
    -- Ensure indexes exist
    CREATE INDEX IF NOT EXISTS idx_app_user_role ON public.app_user(role_id);
    CREATE INDEX IF NOT EXISTS idx_app_user_client ON public.app_user(client_id);
    CREATE INDEX IF NOT EXISTS idx_app_user_auth_user_id ON public.app_user(auth_user_id);
    CREATE INDEX IF NOT EXISTS idx_app_user_email ON public.app_user(email);
    
  END IF;
  
  RAISE NOTICE 'app_user schema migration completed successfully';
END $$;

-- Verify final schema
SELECT 
  column_name, 
  data_type, 
  is_nullable,
  column_default
FROM information_schema.columns 
WHERE table_schema = 'public' 
AND table_name = 'app_user'
ORDER BY ordinal_position;
