-- =========================================================
-- MIGRATION: Fix app_user schema to match code expectations
-- =========================================================
-- The code expects: id (BIGINT), email (TEXT), auth_user_id (UUID)
-- But database.sql has: user_id (UUID) as PK only
-- =========================================================

BEGIN;

-- Step 1: Rename user_id to auth_user_id for clarity
ALTER TABLE public.app_user 
  RENAME COLUMN user_id TO auth_user_id;

-- Step 2: Add id as BIGINT SERIAL PRIMARY KEY
-- First, drop the old PK constraint
ALTER TABLE public.app_user 
  DROP CONSTRAINT app_user_pkey;

-- Add id column as serial
ALTER TABLE public.app_user 
  ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- Step 3: Add email column
ALTER TABLE public.app_user 
  ADD COLUMN email TEXT;

-- Step 4: Recreate the unique constraint on auth_user_id
ALTER TABLE public.app_user 
  ADD CONSTRAINT app_user_auth_user_id_key UNIQUE (auth_user_id);

-- Step 5: Update indexes
DROP INDEX IF EXISTS public.idx_app_user_role;
DROP INDEX IF EXISTS public.idx_app_user_client;

CREATE INDEX idx_app_user_role ON public.app_user(role_id);
CREATE INDEX idx_app_user_client ON public.app_user(client_id);
CREATE INDEX idx_app_user_auth_user_id ON public.app_user(auth_user_id);
CREATE INDEX idx_app_user_email ON public.app_user(email);

-- Step 6: Populate email from auth.users for existing records
UPDATE public.app_user au
SET email = (
  SELECT email 
  FROM auth.users 
  WHERE id = au.auth_user_id
)
WHERE email IS NULL;

-- Step 7: Make email NOT NULL after population
ALTER TABLE public.app_user 
  ALTER COLUMN email SET NOT NULL;

COMMIT;

-- Verify the new structure
COMMENT ON TABLE public.app_user IS 'Profil applicatif lié à Supabase auth.users (schema updated)';
COMMENT ON COLUMN public.app_user.id IS 'ID interne app_user (BIGINT)';
COMMENT ON COLUMN public.app_user.auth_user_id IS 'Reference to auth.users(id) - UUID from Supabase Auth';
COMMENT ON COLUMN public.app_user.email IS 'Email synchronized from auth.users';
