-- =====================================================
-- Migration: Convertir editorial_calendar de strategy_id vers client_id
-- Description: Simplifier la structure pour avoir un lien direct client → calendar
-- =====================================================

-- Étape 1: Sauvegarder l'ancienne structure au cas où
-- CREATE TABLE editorial_calendar_backup AS SELECT * FROM public.editorial_calendar;

-- Étape 2: Supprimer les contraintes et triggers liés à l'ancienne structure
DROP TRIGGER IF EXISTS auto_create_editorial_calendar ON public.social_media_strategy;
DROP TRIGGER IF EXISTS editorial_calendar_updated_at ON public.editorial_calendar;

-- Étape 3: Supprimer les anciennes policies RLS
DROP POLICY IF EXISTS "Users can delete calendars" ON public.editorial_calendar;
DROP POLICY IF EXISTS "Users can insert calendars" ON public.editorial_calendar;
DROP POLICY IF EXISTS "Users can update calendars" ON public.editorial_calendar;
DROP POLICY IF EXISTS "Users can view all calendars" ON public.editorial_calendar;
DROP POLICY IF EXISTS "admin_all_editorial_calendar" ON public.editorial_calendar;
DROP POLICY IF EXISTS "client_select_own_calendars" ON public.editorial_calendar;

-- Étape 4: Supprimer la contrainte FK strategy_id
ALTER TABLE public.editorial_calendar 
  DROP CONSTRAINT IF EXISTS editorial_calendar_strategy_id_fkey;

-- Étape 5: Supprimer la contrainte UNIQUE sur strategy_id
ALTER TABLE public.editorial_calendar 
  DROP CONSTRAINT IF EXISTS editorial_calendar_strategy_unique;

-- Étape 6: Vérifier si la migration n'a pas déjà été appliquée
DO $$
BEGIN
  -- Si editorial_calendar_old existe déjà, la migration a déjà été lancée
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'editorial_calendar_old') THEN
    RAISE NOTICE 'Migration déjà partiellement appliquée - editorial_calendar_old existe';
    -- Supprimer la nouvelle table si elle est vide pour recommencer proprement
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'editorial_calendar') THEN
      DELETE FROM public.editorial_calendar;
    END IF;
  ELSE
    -- Renommer l'ancienne table
    ALTER TABLE public.editorial_calendar RENAME TO editorial_calendar_old;
  END IF;
END$$;

-- Étape 7: Créer la nouvelle table avec client_id (si elle n'existe pas)
DROP TABLE IF EXISTS public.editorial_calendar;
CREATE TABLE public.editorial_calendar (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id         BIGINT NOT NULL REFERENCES public.client(id) ON DELETE CASCADE,
  title             TEXT NOT NULL,
  publish_date      DATE NOT NULL,
  publish_time      TIME,
  platform          TEXT NOT NULL DEFAULT 'instagram',
  objective         TEXT NOT NULL DEFAULT 'engagement',
  strategic_intent  TEXT,
  pillar            TEXT NOT NULL,
  persona           TEXT,
  script_id         BIGINT,
  status            TEXT NOT NULL DEFAULT 'idea'
                    CHECK (status IN ('idea', 'production', 'scheduled', 'published')),
  notes             TEXT,
  color             TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- Étape 8: Migrer les données de l'ancienne table vers la nouvelle
-- Récupérer client_id depuis social_media_strategy
INSERT INTO public.editorial_calendar (
  id, client_id, title, publish_date, pillar, platform, objective, status, created_at, updated_at
)
SELECT 
  eco.id,
  sms.client_id,
  COALESCE(eco.name, 'Calendrier migré'),
  COALESCE(eco.start_date, CURRENT_DATE),
  'Général', -- Pilier par défaut pour les anciennes entrées
  'instagram', -- Platform par défaut
  'engagement', -- Objective par défaut
  'idea', -- Status par défaut
  eco.created_at,
  eco.updated_at
FROM public.editorial_calendar_old eco
JOIN public.social_media_strategy sms ON sms.id = eco.strategy_id
WHERE sms.client_id IS NOT NULL
  AND EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'editorial_calendar_old')
ON CONFLICT (id) DO NOTHING;

-- Étape 9: Réinitialiser la séquence d'ID
-- Vérifier quelle séquence est attachée à la colonne
DO $$
DECLARE
  current_max BIGINT;
BEGIN
  -- Récupérer le max ID actuel
  SELECT COALESCE(MAX(id), 0) INTO current_max FROM public.editorial_calendar;
  
  -- Réinitialiser la séquence (essayer les deux noms possibles)
  BEGIN
    PERFORM setval('public.editorial_calendar_id_seq', current_max);
  EXCEPTION WHEN undefined_table THEN
    -- La séquence n'existe pas avec ce nom, essayer l'autre
    BEGIN
      PERFORM setval(pg_get_serial_sequence('public.editorial_calendar', 'id'), current_max);
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'Impossible de réinitialiser la séquence automatiquement';
    END;
  END;
  
  RAISE NOTICE 'Séquence réinitialisée à %', current_max;
END$$;

-- Étape 10: Créer les index
CREATE INDEX IF NOT EXISTS idx_editorial_calendar_client     ON public.editorial_calendar(client_id);
CREATE INDEX IF NOT EXISTS idx_editorial_calendar_date       ON public.editorial_calendar(publish_date);
CREATE INDEX IF NOT EXISTS idx_editorial_calendar_status     ON public.editorial_calendar(status);
CREATE INDEX IF NOT EXISTS idx_editorial_calendar_platform   ON public.editorial_calendar(platform);
CREATE INDEX IF NOT EXISTS idx_editorial_calendar_pillar     ON public.editorial_calendar(pillar);

-- Étape 11: Trigger updated_at
CREATE OR REPLACE FUNCTION public.update_editorial_calendar_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_editorial_calendar_updated_at
  BEFORE UPDATE ON public.editorial_calendar
  FOR EACH ROW EXECUTE FUNCTION public.update_editorial_calendar_updated_at();

-- Étape 12: RLS
ALTER TABLE public.editorial_calendar ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage editorial_calendar"
ON public.editorial_calendar FOR ALL TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.app_user
    WHERE app_user.auth_user_id = auth.uid()
    AND app_user.role_id = 1
  )
);

-- Étape 13: Supprimer l'ancienne table (décommenter si migration OK)
-- DROP TABLE IF EXISTS public.editorial_calendar_old CASCADE;

-- Commentaires
COMMENT ON TABLE public.editorial_calendar IS 'Calendrier éditorial par client avec posts planifiés';
COMMENT ON COLUMN public.editorial_calendar.client_id IS 'Client propriétaire du calendrier';
COMMENT ON COLUMN public.editorial_calendar.pillar IS 'Pilier de contenu stratégique';
COMMENT ON COLUMN public.editorial_calendar.status IS 'Statut du post: idea, production, scheduled, published';
