-- =========================================================
-- MIGRATION: editorial_calendar
-- Calendrier éditorial par client
-- =========================================================

-- Table principale
CREATE TABLE IF NOT EXISTS public.editorial_calendar (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id         BIGINT NOT NULL REFERENCES public.client(id) ON DELETE CASCADE,
  title             TEXT NOT NULL,
  publish_date      DATE NOT NULL,
  publish_time      TIME,
  platform          TEXT NOT NULL DEFAULT 'instagram',
  objective         TEXT NOT NULL DEFAULT 'engagement',
  strategic_intent  TEXT,
  pillar            TEXT NOT NULL,
  persona           TEXT,
  script_id         BIGINT,
  status            TEXT NOT NULL DEFAULT 'idea'
                    CHECK (status IN ('idea', 'production', 'scheduled', 'published')),
  notes             TEXT,
  color             TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- Index
CREATE INDEX IF NOT EXISTS idx_editorial_calendar_client     ON public.editorial_calendar(client_id);
CREATE INDEX IF NOT EXISTS idx_editorial_calendar_date       ON public.editorial_calendar(publish_date);
CREATE INDEX IF NOT EXISTS idx_editorial_calendar_status     ON public.editorial_calendar(status);
CREATE INDEX IF NOT EXISTS idx_editorial_calendar_platform   ON public.editorial_calendar(platform);
CREATE INDEX IF NOT EXISTS idx_editorial_calendar_pillar     ON public.editorial_calendar(pillar);

-- Trigger updated_at
CREATE OR REPLACE FUNCTION update_editorial_calendar_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_editorial_calendar_updated_at ON public.editorial_calendar;
CREATE TRIGGER trg_editorial_calendar_updated_at
  BEFORE UPDATE ON public.editorial_calendar
  FOR EACH ROW EXECUTE FUNCTION update_editorial_calendar_updated_at();

-- RLS
ALTER TABLE public.editorial_calendar ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage editorial_calendar" ON public.editorial_calendar;
CREATE POLICY "Admins manage editorial_calendar"
ON public.editorial_calendar FOR ALL TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.app_user
    WHERE app_user.auth_user_id = auth.uid()
    AND app_user.role_id = 1
  )
);
